---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update repositories cache on Archlinux
      community.general.pacman:
        update_cache: true
      become: true

    - name: Show ansible version
      ansible.builtin.debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

  roles:
    - role: ansible-rclone
