---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "rclone-${image:-archlinux}-${tag:-latest}-${TOX_ENVNAME}"
    image: "carlodepieri/docker-archlinux-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    ulimits:
      - nofile:65535:65535
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      instance:
        rclone_release: ${TEST_RELEASE:-stable}
        rclone_version: ${TEST_VERSION:-''}
