---
- name: Get rclone beta version
  unarchive:
    src: "{{ beta_version_url | default('https://beta.rclone.org/v' + rclone_version + '/rclone-v' + rclone_version + '-linux-' + rclone_arch + '.zip') }}"
    dest: "{{ rclone_setup_tmp_dir }}"
    remote_src: true
    mode: 0744
    list_files: true
    creates: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}"
