---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.     # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_distribution == 'Fedora'
      changed_when: false

    - name: Show ansible version
      debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

  roles:
    - role: ansible-rclone
