---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Wait for systemd to complete initialization.     # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts.distribution == 'Fedora'
      changed_when: false

    - name: Show ansible version
      ansible.builtin.debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

  roles:
    - role: ansible-rclone
