---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update apt cache on Debian Linux.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Update repositories cache on Archlinux.
      community.general.pacman:
        update_cache: true
      when: ansible_facts.os_family == 'Archlinux'
      register: pacman_result
      changed_when: pacman_result.cache_updated
      become: true

    - name: Wait for systemd to complete initialization.     # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts.distribution == 'Fedora'
      changed_when: false
      check_mode: false

    - name: Show ansible version
      ansible.builtin.debug:
        msg: "Ansible Version: {{ ansible_version.full }}"

  roles:
    - role: stefangweichinger.ansible_rclone
