---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "rclone-${image:-debian12}-${TOX_ENVNAME}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: "rclone-archlinux"
    image: "carlodepieri/docker-archlinux-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    ulimits:
      - nofile:65535:65535
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      instance:
        rclone_release: ${TEST_RELEASE:-stable}
        rclone_version: ${TEST_VERSION:-''}
      rclone-archlinux:
        ansible_user: ansible
