---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Fix /etc/shadow
      register: etc_shadow
      ansible.builtin.shell:
        cmd: |
          echo ""
          ls -l /etc/shadow
          chmod 0400 /etc/shadow
          ls -l /etc/shadow
          echo ""

    - name: Print /etc/shadow
      ansible.builtin.debug:
        var: etc_shadow.stdout
