---

name: Bump version

on:
  push:
    branches:
      - main
      - play_with_cz

jobs:

  pre-commit:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install --upgrade --requirement requirements-test.txt
        pip install --upgrade pre-commit
    - name: Set up pre-commit hook environments
      run: pre-commit install-hooks
    - name: Run pre-commit on all files
      run: pre-commit run --all-files

  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
